version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: yourpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - .env
    volumes:
      - ./service-a:/service-a
      - service-a-node-modules:/service-a/node_modules

volumes:
  rabbitmq_data:
  mongo_data:
  service-a-node-modules:
